### ISSUE TITLE
Best practice for using i18n with strings in Rails 4 model?

### ISSUE THREAD

**Issue by reconstructions** [abitdodgy/i18n_lazy_scope#2]
I really like your gem.

I am running into a little problem with moving some of the strings from my model validators into `en.yml`.  If I use the typical `t` approach (`I18n.t('models.band.band_name_validation')` I get the following in my view:

``` html
<span class="translation_missing" title="translation missing: en.views.bands.index.title">Title</span>:
```

Since I am calling this from my model I am wondering why `t` is looking in `views.bands.index.title` when I have this in my `en.yml`.  It seems like maybe some of your gem's magic might be tripping things up?

``` yml
en:
  models:
    band:
      band_name_validation: "Dude, you gotta have a band name!"
```

I tried calling `I18nLazyScope.t_scoped` from my model and that was `undefined method 't_scoped'`.  I also tried using `t_scoped("band_name_validation")`, and that was also `undefined method 't_scoped'`.  Is there a reason why I am not able to use `t` in my model with your gem installed?  I also tried using `model:` instead of `models:` in my .yml, but no luck.

Can you tell me how to get this done using your gem or `t`?  Thanks in advance.

I also wish there was a way I could use aliases over multiple .yml files so I could divide up my massive single file into folders.  Can't find any way to do this now, maybe it's not even possible, but I would love to see a gem for that.

**Comment by abitdodgy** [comment]
@reconstructions hello there! Cheers, I'm glad you are finding it useful. The reason why you are running into this issue is because the first release includes translations for controllers, mailers, and views, but not models. I never got around to adding model level since a use case never came up.

One of the reasons why the model layer wasn't included is because we don't usually use I18n from the model. In most cases, there's a better way.

For example, if you want to translate a an attribute in the view, you would use `Person.human_attribute_name("first_name")` ([see here](http://apidock.com/rails/ActiveRecord/Base/human_attribute_name/class)). If you were sending out an email from the model, the mailer can handle all the translations. If you are using custom validation messages, like in your case, Rails has already solved that by including an ActiveRecord errors namespace:

``` yaml
en:
  activerecord: 
    errors:
      models:
        band:
          bad_name_validation_msg: "This is i18n controlled. yay!"
```

Then in your model, you would use:

``` ruby
validate :band_name_validation

def band_name_validation
    errors.add(:band_name, :bad_name_validation_msg)  if error_condition
end
```

As you can see, you don't have to qualify the scope or even use I18n. You can just pass a symbol that represents the message key, and place the message under the `lang.activerecord.errors.models.model_name.message_key` scope.

I'm sure there may be instances where you do need to translate from the model, but I've never personally ran into one. Let me know if you feel that this is necessary.

As for the `undefined method t_scoped`, error, this is because it's not defined on ActiveRecord, only on ActionView, ActionController, and ActionMailer.

Cheers!

**Comment by reconstructions** [comment]
My case was a custom validation, but I didn't find the active record usage you documented anywhere else.  Thanks for that, it was just what I was looking for.
